name: Run Checks

permissions:
  contents: read
on:
  workflow_call:
    secrets:
      VAULT_URL:
        required: true
      CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN:
        required: true
      CLI_E2E_ORG_ID:
        required: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          npx allow-scripts

      - name: Restore the build folders
        uses: actions/cache/restore@v4
        with:
          path: |
            dist
            build
          key: build-cache-${{ github.run_id }}-${{ github.run_attempt }}

      # Prior ci publishing did not lint or format, commented out to preserve workflow
      # - name: Run linter
      #   run: npm run lint

      #- name: Check formatting
      #  run: npm run prettier:check
      #  env:
      #    CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN: ${{ secrets.CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN }}
      #    CLI_E2E_ORG_ID: ${{ secrets.CLI_E2E_ORG_ID }}

      - name: Run unit tests
        run: npm test
        env:
          CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN: ${{ secrets.CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN }}
          CLI_E2E_ORG_ID: ${{ secrets.CLI_E2E_ORG_ID }}

      - name: Run integration tests
        run: npm run test:integration:ci
        env:
          CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN: ${{ secrets.CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN }}
          CLI_E2E_ORG_ID: ${{ secrets.CLI_E2E_ORG_ID }}
